import "./globals.css";
import {Outfit} from "next/font/google"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfitFont = Outfit({
  subsets:['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfitFont.className}
      >
        {children}
      </body>
    </html>
  );
}
